feat(service): compatibility with old service system (initctl)
ChristopherDavenport/ansible-role-universal-tomcat pull request #19
Opened 2017-04-10 13:26 UTC by lparet-yseop

you can contact me by email : lparet@yseop.com

2017-04-11 00:42 UTC, ChristopherDavenport requested changes
Overall I really like these changes and would like to incorporate them. 

Roles should be idempotent, so that they have guaranteed consistency, and owners can know the state of their inventory.

This is definitely a great start!

2017-04-11 00:42 UTC, ChristopherDavenport commented on tasks/main.yml
> +    - new_version
Tags are not `when` looped so by default both loops will execute and will have to be programatically known by the runner.

Seems like an ideal place to build out a service matrix, or at least a check to see which is better to run of some sort.

2017-04-11 00:42 UTC, ChristopherDavenport commented on tasks/service_ctl_tomcat.yml
> +  command: initctl reload-configuration
Command Module is Non-Idempotent by default. Definitely needs a `when` clause when the service installation changed. Also does this do the same thing as the service module with `state:reloaded`

2017-04-11 00:42 UTC, ChristopherDavenport commented on tasks/service_systemd_tomcat.yml
> +  systemd:
As I stated above, if this runs every time I believe this will fail the role on a system without systemd.

2017-04-11 08:44 UTC, lparet-yseop commented on tasks/main.yml
> +    - new_version
https://github.com/ChristopherDavenport/ansible-role-universal-tomcat/pull/19/commits/fcc6d71d3affe2a3bcc3dbdd1db1a888e565e489

2017-04-11 08:44 UTC, lparet-yseop commented on tasks/service_ctl_tomcat.yml
> +  command: initctl reload-configuration
https://github.com/ChristopherDavenport/ansible-role-universal-tomcat/pull/19/commits/904359218ded7f76c98767763d20e0a310fdfae7

2017-04-11 08:44 UTC, lparet-yseop commented on tasks/service_systemd_tomcat.yml
> +  systemd:
https://github.com/ChristopherDavenport/ansible-role-universal-tomcat/pull/19/commits/fcc6d71d3affe2a3bcc3dbdd1db1a888e565e489

2017-04-11 08:48 UTC, lparet-yseop commented
I readed your return and I try to fix what you proposed
If you have other returns to improive this role I could do changes myself

I'm learning Ansible and it is a really good training for me 
Thanks !

2017-04-11 11:51 UTC, lparet-yseop commented
I commit yet to change the way to check the init system used
with stat on /sbin/init I can know if it's initctl (itsn't a symbolic link) if it's systemd (it's a symbolic link and the source contains "systemd")
For the future, We can add check to detect other init system

2017-04-11 14:00 UTC, ChristopherDavenport commented
So if you're willing to go all the way with this, I'm currently pushing an updated Travis build that I will issue as a PR against your build. The build includes multiple Init Based Systems that are currently failing with that current role build.

2017-04-12 15:34 UTC, lparet-yseop commented
Few tests failed, I don't know why yet 
But do you thing 10 seconds is sufficient for old OS version ? It's just a hypothesis

2017-04-12 15:49 UTC, ChristopherDavenport commented
Easiest way is to take the end of the travis script and run it locally and increase the wait time in `test.yml` to see if there are any changes. I will have more time to investigate this evening in more depth.

2017-04-13 08:50 UTC, lparet-yseop commented
Ok keep me informed if you have more informations
Thank you and have a nice day

2017-04-13 13:13 UTC, ChristopherDavenport commented
So here is my debugging for issues like this, and if you are getting frustrated let me know I can give more push. 

The basic problem is that the server is not starting as expected on it systems, even after checking and getting a correct message about the service starting. As a result, I would in order to test put a command that captures the tomcat log file such as  `cat /opt/tomcat/logs/catalina.out` and then put stout_lines as a debug. This allows you to see the internal working of tomcat in regards to your role. You would want to use travis, on a different non-merging branch for that work, or to do it with the docker commands locally. This would allow you to know more about what is occuring with tomcat besides the more obvious information that is is not allowing access to the manager app.

2017-04-18 08:22 UTC, appcara-kaminglau commented
I have similar requirement to support non-systemd OS. Perhaps a better way would be to use include_vars for different distro but I think as a quick touch up this works for me.

https://github.com/appcara-kaminglau/ansible-role-universal-tomcat/commit/ab403f6a313aa31a532297cd7fa97bf788bf7c25

2017-04-18 13:33 UTC, lparet-yseop commented
The problem is that Docker container can't have systemctl. That's why it works only on recent version of Linux and not with old version (Ubuntu 14 and 12, EL6 and OracleLinux 6)
I tested on classic VM and it's ok...
In my last commit, I tried to create a system which check if we are in a docker container but the solution isn't idempotent. I can't create tomcat as a service... Do you have an idea to do that ?

I am working on VM so for me it works, but here the problem is with Docker...

2017-04-19 17:01 UTC, ChristopherDavenport approved these changes
Here's what we'll do, comment out failing builds and add support with an Experimental tag in the README, since support is still good for systemctl. 

We can work on building something that works more conclusively as a separate issue. The work required to make this operate smoothly may be in [AnsibleCheck](https://github.com/AnsibleCheck/ansiblecheck) rather than this repository. However if we have a working solution I am apt to bring it in and improve moving forward.

When CI passes with those changes we will merge.

2017-04-27 13:38 UTC, ChristopherDavenport commented
Do you want me to push the requested fixes in for you? I don't want to step on your toes, but I'd like to get this merged.

2017-05-02 09:09 UTC, lparet-yseop commented
Yes if you want, I need it too but I don't want to push errors :)
(Sorry for the response time)

2017-05-02 12:42 UTC, ChristopherDavenport commented
I'll get on it ASAP.

2017-05-12 16:04 UTC, ChristopherDavenport commented
Sorry it took me so long to get back to this.

2017-05-12 16:21 UTC, merged

2017-05-15 08:21 UTC, lparet-yseop commented
It works for me, thk !
Normally I will send you an other PR to add other init system compatibility